#!/bin/bash

RED='\033[1;31m'
GREEN='\033[1;32m'
BLUE='\033[1;34m'
PURPLE='\033[1;35m'
NC='\033[0m'

echo "Lemme check ya code.."
src/gradlew spotlessCheck || { echo -e "${RED}Nop, ${NC}format pls p(@.@)"; exit 1; }

echo -e "${GREEN}B${BLUE}e${PURPLE}A${BLUE}u${GREEN}T${BLUE}i${PURPLE}F${BLUE}u${GREEN}L${BLUE}${NC}! (@.<)b"
exit 0

