#!/bin/bash

commit_msg_file="$1"
commit_source="$2"
sha1="$3"

issue_pattern='#[0-9]+'

commit_msg=$(cat "$commit_msg_file")

if [[ $commit_msg =~ $issue_pattern ]]; then
    exit 0
else
    echo "Nop, no GitLab issue # was found in commit message p(@.@)"
    exit 1
fi

